//
// FruitNutritions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FruitNutritions: Codable, JSONEncodable, Hashable {

    public var calories: Double
    public var fat: Double
    public var sugar: Double
    public var carbohydrates: Double
    public var protein: Double

    public init(calories: Double, fat: Double, sugar: Double, carbohydrates: Double, protein: Double) {
        self.calories = calories
        self.fat = fat
        self.sugar = sugar
        self.carbohydrates = carbohydrates
        self.protein = protein
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calories
        case fat
        case sugar
        case carbohydrates
        case protein
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(calories, forKey: .calories)
        try container.encode(fat, forKey: .fat)
        try container.encode(sugar, forKey: .sugar)
        try container.encode(carbohydrates, forKey: .carbohydrates)
        try container.encode(protein, forKey: .protein)
    }
}

